-- Phase 2 — double-entry journal.
-- journal_entries = one posting per accepted trade.
-- journal_lines   = the mirrored debit/credit lines that must balance.

CREATE TABLE journal_entries (
    journal_entry_id UUID PRIMARY KEY,
    -- Idempotency key (== trades.request_id). UNIQUE guarantees no double-post,
    -- enforced by the database itself, not just application code.
    source_event_id  UUID NOT NULL UNIQUE,
    account_id       VARCHAR(64) NOT NULL REFERENCES accounts(account_id),
    posted_at        TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_journal_entries_account_id ON journal_entries(account_id);
CREATE INDEX idx_journal_entries_posted_at  ON journal_entries(posted_at);

CREATE TABLE journal_lines (
    line_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_entry_id UUID NOT NULL REFERENCES journal_entries(journal_entry_id),
    account_ref      VARCHAR(64) NOT NULL,           -- 'securities' or an account_id
    debit            NUMERIC(20, 4) NOT NULL DEFAULT 0,
    credit           NUMERIC(20, 4) NOT NULL DEFAULT 0,
    CONSTRAINT chk_lines_debit_non_negative  CHECK (debit >= 0),
    CONSTRAINT chk_lines_credit_non_negative CHECK (credit >= 0),
    -- Each line is exactly one of a debit or a credit (never both, never neither).
    CONSTRAINT chk_lines_debit_xor_credit
        CHECK ((debit > 0 AND credit = 0) OR (credit > 0 AND debit = 0))
);

CREATE INDEX idx_journal_lines_entry ON journal_lines(journal_entry_id);
